builds:
  - binary: openio.plugin
    main: openio.plugin.go
    flags: "-gccgoflags '-static'"
    goos:
      - linux
    goarch:
      - amd64
  - binary: zookeeper.plugin
    main: zookeeper.plugin.go
    flags: "-gccgoflags '-static'"
    goos:
      - linux
    goarch:
      - amd64
  - binary: container.plugin
    main: container.plugin.go
    flags: "-gccgoflags '-static'"
    goos:
      - linux
    goarch:
      - amd64

archive:
  wrap_in_directory: false
  name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}"

release:
  github:
    owner: vdombrovski
    name: openio-netdata
  draft: true
  prerelease: true
  name_template: "v{{.Version}}"
